version: "3"

services:
  database_ignite:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    container_name: database_ignite
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ignite
      POSTGRES_DB: rentx
  #app:
  #build:
  #context: .
  #container_name: rentx
  #restart: always
  #ports:
  #- 3333:3333
  #volumes:
  #- ./src:/app/src

volumes:
  pgdata:
